rails-app/config/routes.rb
RailsApp::Application.routes.draw do

  devise_for :users, :skip => [:registrations, :confirmations]
  devise_scope :user do
    get 'sign-in' => 'devise/sessions#new', :as => :new_user_session
    post 'sign-in' => 'devise/sessions#create', :as => :user_session
    match 'get-out' => 'devise/sessions#destroy', :as => :destroy_user_session

    post 'sign-up' => 'devise/registrations#create', :as => :user_registration
    get 'sign-up' => 'devise/registrations#new', :as => :new_user_registration
    get 'sign-up/edit' => 'devise/registrations#edit', :as => :edit_user_registration
  end

  resources :users
  resources :products

  root to: "welcome#index"
  get "welcome/index"

end

rails-app/app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :preview, :file
  has_one :user

  mount_uploader :preview, ProductFilePreviewUploader
  mount_uploader :file, ProductFileUploader
end

rails-app/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :products
end

rails-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

rails-app/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!
  def new
    @product = Product.new
  end

  def edit
  end

  def index
    @products = Product.all
  end

  def create
    
    new_product = current_user.products.build(params[:product])
    saved = new_product.save

    if saved
      flash[:notice] = "Successful upload!"
      redirect_to :action => :index
      return
    end

    raise "didn't save"

  end
  def update
  end
  def delete
  end

end

rails-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :set_user

  def show
    @bought_items = []
    @products = @user.products
  end

  def update
    @user.update_attributes(params[:user])
    @user.save

    flash[:notice] = "Your name has been updated!"

    redirect_to @user
  end
  def edit
  end


  private

  def set_user
    @user = current_user
  end

  def post_params
    request.POST.slice([:name])
  end

end

rails-app/app/controllers/welcome_controller.rb
require 'ostruct'

class WelcomeController < ApplicationController
  def index
    @popular_products = Product.all
    @picked_products = Product.all
  end
end

rails-app/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-app/app/helpers/products_helper.rb
module ProductsHelper
end

rails-app/app/helpers/users_helper.rb
module UsersHelper
end

rails-app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

rails-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>AnimateFour</title>

	<%= csrf_meta_tag %>

	<link rel="stylesheet" href="/media/vendor/foundation/css/normalize.css" />
	<link rel="stylesheet" href="/media/css/foundation.css" />
	<link rel="stylesheet" href="/media/css/main.css" />
	

	<script src="/media/vendor/jquery/jquery.min.js"></script>
	<script src="/media/vendor/modernizr/modernizr.js"></script>
	<script src="/media/vendor/foundation/js/foundation.min.js"></script>

</head>
<body>

<% content_for :alert do %>
	<% if notice %><p class="top-alert alert-box info"><%= notice %></p><% end %>
	<% if alert %><p class="top-alert alert-box warning"><%= alert %></p><% end %>
<% end %>

<!-- This is until it needs to be something reasonable, so at least i can see when there are problems -->
<%= yield(:alert) %>

<div id="main-top-bar-container" class="contain-to-grid">
	<nav class="top-bar" data-topbar>
		<ul class="title-area">
			<li class="name">
				<h1><a href="/">AnimateFour</a></h1>
			</li>
			<li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
		</ul>

		<section class="top-bar-section">
			<!-- Right Nav Section -->
			<ul class="right">
				<% if user_signed_in? %>
				<li class="has-dropdown">
					<a href="<%= user_path(current_user.id) %>">Hey <%= current_user.email %></a>
					<ul class="dropdown">
						<li><a href="<%= new_product_path %>">Add Product</a></li>
						<li><a href="<%= destroy_user_session_path %>">Sign Out</a></li>
					</ul>
				</li>
				<% else %>
				<li class="active">
					<a href="<%= new_user_session_path %>">Sign in</a>
				</li>
				<% end %>

			</ul>

		</section>
	</nav>
</div>
<script>
$('#main-top-bar-container').foundation();
</script>


<div class="row">

<%= yield %>

</div>



</body>
</html>

rails-app/app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

rails-app/app/views/products/index.html.erb
<h1>Products</h1>

<ul>
	<% @products.each do |product| %>
	<li>
		<h5><%= product.name %></h5>
		<div>
			<img src="<%= product.preview %>"/>
			<aside><b>Preview</b> - <%= product.preview %></aside>
		</div>
		<p><b>File</b> - <%= product.file %></p>
	</li>
	<% end %>
</ul>

rails-app/app/views/products/new.html.erb
<h1>Make a new thingy!</h1>

<%= form_for(@product, :action => :create) do |f| %>
	
	<%= f.text_field(:name, :placeholder=>"Name") %>
	
	<%= f.label(:preview) %>
	<%= f.file_field(:preview) %>
	
	<%= f.label(:file) %>
	<%= f.file_field(:file) %>
	
	<button class="button" type="submit">Create new product</button>
<% end %>

rails-app/app/views/users/edit.html.erb
<a href="<%= user_path(@user) %>" class="button tiny">Back</a>
<h2>Edit yourself</h2>

<%= form_for @user, :url => {:action => "update"} do |f| %>
	<label>Name</label>
	<%= f.text_field :name %>

	<%= f.submit "Save that crap", :class => "button" %>
<% end %>

rails-app/app/views/users/show.html.erb
<div class="large-12 columns">
	<div class="row">
		<a class="button tiny right" href="<%= edit_user_path(@user) %>">edit</a>
		<% if @user.name && @user.name != "" %>
			<h1><%= @user.name %>, <small>you've done things.</small></h1>
		<% else %>
			<div class="medium-6 columns">
				<%= form_for @user, :url => {:action=>:update}, :html => {:class => "callout-form"} do |f| %>
					<div class="row collapse">
						<div class="medium-8 columns">
							<%= f.text_field :name, :placeholder=>"You have no name." %>
						</div>
						<div class="medium-4 columns">
							<button type="submit" class="button postfix">Set it</button>
						</div>
					</div>
				<% end %>
			</div>
		<% end %>
	</div>

	<div class="row">
		<div class="medium-6 columns">
			<h3>Things you created</h3>

			<% if @products.length <= 0 %>
				<p class="alert-box info">Nothing.</p>
			<% else %>
				<ul class="block-grid">
					<% @products.each do |product| %>
					<li>
						<h5><%= product.name %></h5>
						<div>
							<img src="<%= product.preview %>"/>
							<aside><b>Preview</b> - <%= product.preview %></aside>
						</div>
						<p><b>File</b> - <%= product.file %></p>
					</li>
					<% end %>
				</ul>
			<% end %>
		</div>
		<div class="medium-6 columns">
			<h3>Things you bought</h3>

			<% if @bought_items.length <= 0 %>
				<p class="alert-box info">Nothing.</p>
			<% else %>
				<ul class="block-grid">
					<% @bought_items.each do |item| %>
					<li>
						<h5><%= item.title %></h5>
					</li>
					<% end %>
				</ul>
			<% end %>
		</div>
	</div>
</div>

rails-app/app/views/welcome/index.html.erb
<div class="row">
	<h3>Popular</h3>
	<ul class="small-block-grid-3">
		<% @popular_products.each do |product| %>
		<li>
			<h5><%= product.name %></h5>
		</li>
		<% end %>
	</ul>
</div>

<div class="row">
	<h3>Hand-picked</h3>
	<ul class="small-block-grid-3">
		<% @picked_products.each do |product| %>
		<li>
			<h5><%= product.name %></h5>
		</li>
		<% end %>
	</ul>
</div>